const initialState = {
  map: [
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '20,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '30,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '40,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '25,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '22,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '26,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      gray: true,
      manaSymbol: true,
      mana: '28,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '23,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '27,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '28,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '28,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '29,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '30,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '22,000',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '20,300',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '20,100',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '20,400',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '20,400',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      manaSymbol: true,
      mana: '20,600',
    },
    {
      name: 'Plaza',
      months: '4',
      num: '1',
      x: '20',
      y: '-30',
      green: true,
      blue: true,
      gray: true,
      manaSymbol: true,
      mana: '3,000',
    },
  ],
};

export default (state = initialState, { type, payload }) => {
  switch (type) {
    default:
      return state;
  }
};
